use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct S3Settings {
    pub bucket: String,
    pub region: String,
    pub endpoint: String,
    pub access_key: String,
    pub secret_key: String,
}

/// Render `pgbackrest.conf` for one instance. Each instance gets its own
/// `repo1-path` (`/pgforge/<instance>`) so a single S3 bucket can host many.
///
/// `retain_days = 0` disables retention (keep all full backups forever).
/// Any positive value enables time-based retention via
/// `repo1-retention-full-type=time` + `repo1-retention-full=N`, where N is
/// the number of days. pgbackrest auto-prunes WAL needed for expired
/// fulls, so R2 storage stays bounded.
pub fn generate_pgbackrest_conf(instance_name: &str, s3: &S3Settings, retain_days: u32) -> String {
    let retention_block = if retain_days == 0 {
        "# Retention disabled (retain_days = 0): full backups kept forever.\n".to_string()
    } else {
        format!(
            "repo1-retention-full={days}\n\
             repo1-retention-full-type=time\n",
            days = retain_days,
        )
    };
    format!(
        r#"# Generated by pgforge — do not edit by hand.

[global]
# --- Repository: S3 ---------------------------------------------------------
repo1-type=s3
repo1-s3-bucket={bucket}
repo1-s3-region={region}
repo1-s3-endpoint={endpoint}
repo1-s3-key={akey}
repo1-s3-key-secret={skey}
repo1-s3-uri-style=host
repo1-path=/pgforge/{instance}
repo1-cipher-type=none
repo1-storage-verify-tls=y

# --- Retention --------------------------------------------------------------
{retention}
# --- Performance / archiving ------------------------------------------------
compress-type=zst
compress-level=3
process-max=4
archive-async=y
spool-path=/var/spool/pgbackrest
start-fast=y
stop-auto=y

# --- Logging ----------------------------------------------------------------
log-path=/var/log/pgbackrest
log-level-console=info
log-level-file=detail

[global:archive-push]
process-max=2

[main]
pg1-path=/var/lib/postgresql/data/pgdata
pg1-port=5432
pg1-user=pgbackrest
pg1-database=postgres
pg1-socket-path=/var/run/postgresql
"#,
        bucket = s3.bucket,
        region = s3.region,
        endpoint = s3.endpoint,
        akey = s3.access_key,
        skey = s3.secret_key,
        instance = instance_name,
        retention = retention_block,
    )
}
