/// Render the entrypoint script bind-mounted into a clone container. If
/// PGDATA is empty (first start), pg_basebackup from the source container
/// over the docker bridge. Then chain into the official postgres entrypoint.
pub fn generate_clone_entrypoint(source_container: &str) -> String {
    format!(
        r#"#!/bin/sh
# Generated by pgforge — do not edit by hand.
set -eu

PGDATA="/var/lib/postgresql/data/pgdata"
export PGPASSFILE=/var/lib/postgresql/.pgpass

# Clone only if the data directory is empty / has no PG cluster yet.
if [ ! -f "$PGDATA/PG_VERSION" ]; then
    mkdir -p "$PGDATA"
    chown -R postgres:postgres "$PGDATA"
    su - postgres -c 'PGPASSFILE=/var/lib/postgresql/.pgpass pg_basebackup -h {source} -p 5432 -U pgbackrest -D /var/lib/postgresql/data/pgdata -X stream -P --wal-method=stream --no-password'
fi

exec docker-entrypoint.sh postgres
"#,
        source = source_container
    )
}
