/// Render the entrypoint script bind-mounted into a restore container. If
/// PGDATA is empty (first start), run `pgbackrest restore`; then chain into
/// the official postgres entrypoint regardless. The script runs as root via
/// the postgres image's default entrypoint mechanism; the inner `su -` calls
/// drop privileges to the `postgres` user where needed.
pub fn generate_restore_entrypoint(target_time: Option<&str>) -> String {
    let target_args = match target_time {
        Some(t) => format!(
            r#" --type=time --target="{t}" --target-action=promote"#
        ),
        None => " --target-action=promote".to_string(),
    };
    format!(
        r#"#!/bin/sh
# Generated by pgforge — do not edit by hand.
set -eu

PGDATA="/var/lib/postgresql/data/pgdata"

# Restore only if the data directory is empty / has no PG cluster yet.
if [ ! -f "$PGDATA/PG_VERSION" ]; then
    mkdir -p "$PGDATA"
    chown -R postgres:postgres "$PGDATA"
    su - postgres -c 'pgbackrest --stanza=main restore --pg1-path=/var/lib/postgresql/data/pgdata{target_args}'
fi

exec docker-entrypoint.sh postgres \
    -c config_file=/etc/postgresql/postgresql.conf \
    -c hba_file=/etc/postgresql/pg_hba.conf
"#,
        target_args = target_args
    )
}
