/// Render the entrypoint script bind-mounted into a restore container. If the
/// marker file is absent (first start or failed previous attempt), run
/// `pgbackrest restore` and write the marker only on success; then chain into
/// the official postgres entrypoint regardless. The script runs as root via
/// the postgres image's default entrypoint mechanism; the inner `su -` calls
/// drop privileges to the `postgres` user where needed.
///
/// The marker (`$PGDATA/.pgforge-restore-complete`) is written AFTER pgbackrest
/// returns 0. A failed or partial restore leaves `PG_VERSION` behind in pgdata;
/// using `PG_VERSION` as the guard would cause a retry to skip restore and boot
/// a corrupt cluster. The marker is absent in that case, so the retry proceeds.
pub fn generate_restore_entrypoint(target_time: Option<&str>) -> String {
    // The script runs under `set -u`. restore.rs only injects the
    // PGFORGE_TARGET container env var when a --target-time is given, so the
    // no-target branch must not reference $PGFORGE_TARGET at all. `su -`
    // resets the environment, so in the target case the value is forwarded
    // explicitly into the postgres user's command.
    let (target_block, restore_cmd) = if target_time.is_some() {
        (
            r#"TARGET_ARGS="--type=time --target=$PGFORGE_TARGET --target-action=promote""#,
            r#"su - postgres -c "PGFORGE_TARGET=$PGFORGE_TARGET pgbackrest --stanza=main restore --pg1-path=/var/lib/postgresql/data/pgdata $TARGET_ARGS""#,
        )
    } else {
        // Restore to latest archived WAL: no recovery target. pgbackrest
        // rejects --target-action unless --type is also set, so it is omitted
        // entirely — postgres auto-promotes once archive recovery reaches
        // end-of-WAL (pgbackrest writes recovery.signal, not standby.signal).
        (
            "# Restore to latest WAL — no recovery target; postgres auto-promotes.",
            r#"su - postgres -c "pgbackrest --stanza=main restore --pg1-path=/var/lib/postgresql/data/pgdata""#,
        )
    };
    format!(
        r#"#!/bin/sh
# Generated by pgforge — do not edit by hand.
set -eu

PGDATA="/var/lib/postgresql/data/pgdata"
MARKER="$PGDATA/.pgforge-restore-complete"

{target_block}

# Marker is written ONLY after pgbackrest restore returns 0. A failed or
# partial restore leaves PG_VERSION behind in pgdata — without the marker
# we retry instead of booting a broken cluster.
if [ ! -f "$MARKER" ]; then
    mkdir -p "$PGDATA"
    chown -R postgres:postgres "$PGDATA"
    # Clear any half-restored content; pgbackrest restore --delta would also
    # work but we want a strict re-do here.
    find "$PGDATA" -mindepth 1 -delete 2>/dev/null || true
    {restore_cmd}
    touch "$MARKER"
    chown postgres:postgres "$MARKER"
fi

exec docker-entrypoint.sh postgres \
    -c config_file=/etc/postgresql/postgresql.conf \
    -c hba_file=/etc/postgresql/pg_hba.conf
"#,
        target_block = target_block,
        restore_cmd = restore_cmd,
    )
}
