/// Render the entrypoint script for a one-shot `pg_upgrade` container. The
/// container has BOTH `from_ver` and `to_ver` postgres binaries (see
/// `image::upgrade_dockerfile`) plus pgbackrest. It mounts:
///   /old/pgdata  — the existing instance's volume, read-write
///   /new/pgdata  — a fresh empty volume that becomes the upgraded cluster
///
/// Steps:
///   1. As postgres, initdb the new datadir with `to_ver` binaries.
///   2. As postgres, run `pg_upgrade` (NOT --link — we want the old vol to
///      survive in its original state for rollback).
///   3. Write a marker file `/new/pgdata/.pgforge-upgrade-complete` so the
///      caller can verify the upgrade actually finished.
///
/// On any step failure the script exits non-zero (via `set -eu`) — the
/// caller (`upgrade.rs`) sees this via `wait_container` exit code and
/// triggers rollback.
pub fn generate_upgrade_entrypoint(from_ver: u8, to_ver: u8) -> String {
    format!(
        r#"#!/bin/sh
# Generated by pgforge — do not edit by hand.
set -eu

FROM_BIN=/usr/lib/postgresql/{from}/bin
TO_BIN=/usr/lib/postgresql/{to}/bin
OLD_PGDATA=/old/pgdata
NEW_PGDATA=/new/pgdata
MARKER="$NEW_PGDATA/.pgforge-upgrade-complete"

# Old PGDATA must NOT be in-use (caller stopped and removed the old container
# before scheduling this upgrade). pg_upgrade refuses otherwise.
chown -R postgres:postgres "$NEW_PGDATA"
chmod 0700 "$NEW_PGDATA"

# 1. Initialize the new cluster with the to-version's binaries.
su - postgres -c "$TO_BIN/initdb --pgdata=$NEW_PGDATA --auth-local=trust --auth-host=scram-sha-256 --encoding=UTF8"

# 2. Run pg_upgrade. Use the postgres user's home for the working dir
# (pg_upgrade writes log files there).
cd /tmp
su - postgres -c "cd /tmp && $TO_BIN/pg_upgrade \
    --old-bindir=$FROM_BIN \
    --new-bindir=$TO_BIN \
    --old-datadir=$OLD_PGDATA \
    --new-datadir=$NEW_PGDATA"

# 3. Write success marker.
touch "$MARKER"
chown postgres:postgres "$MARKER"
echo "pgforge-upgrade-ok"
"#,
        from = from_ver,
        to = to_ver,
    )
}
