use crate::domain::preset::Preset;

/// Render a complete `postgresql.conf` for the given preset. Pure function —
/// no IO, deterministic output. WAL archiving to S3/pgbackrest is enabled by
/// default; pass false to `with_archive` for `--no-backup` (local dev) instances.
pub fn generate_postgresql_conf(preset: Preset) -> String {
    generate_postgresql_conf_with_archive(preset, true)
}

/// Variant that lets the caller disable archiving for instances created
/// without pgbackrest (e.g. `pgforge create --no-backup`).
pub fn generate_postgresql_conf_with_archive(preset: Preset, with_archive: bool) -> String {
    let t = preset.tuning();
    // Postgres runs inside a Linux container regardless of host OS. fdatasync
    // is the only valid wal_sync_method for that container.
    let wal_sync_method = "fdatasync";
    let archive_block = if with_archive {
        r#"# ----- Archiving (pgBackRest, async push to S3) -----------------------------
archive_mode = on
archive_command = 'pgbackrest --stanza=main archive-push %p'
archive_timeout = 60"#
    } else {
        r#"# ----- Archiving -------------------------------------------------------------
# Disabled: instance created with --no-backup (local dev / test). pgbackrest
# is not configured, so archive_command would fail every WAL segment.
archive_mode = off"#
    };

    format!(
        r#"# Generated by pgforge — do not edit by hand. Regenerate via `pgforge create` or `pgforge reconfigure`.
#
# Preset: {preset:?}
# RAM budget: {ram} MB
#

# ----- Connections ----------------------------------------------------------
listen_addresses = '*'
port = 5432
max_connections = {max_conn}
superuser_reserved_connections = 3

# ----- Memory ---------------------------------------------------------------
shared_buffers = {sb}MB
effective_cache_size = {ec}MB
work_mem = {wm}MB
maintenance_work_mem = 64MB

# ----- WAL / Durability -----------------------------------------------------
fsync = on
synchronous_commit = on
full_page_writes = on
wal_compression = on
wal_sync_method = {wsm}
wal_level = replica
max_wal_size = {mws}MB
min_wal_size = 256MB
checkpoint_timeout = 15min
checkpoint_completion_target = 0.9

{archive_block}

# ----- Security -------------------------------------------------------------
ssl = off
password_encryption = scram-sha-256

# ----- Logging --------------------------------------------------------------
log_destination = 'stderr'
logging_collector = on
log_directory = '/var/log/postgresql'
log_filename = 'postgresql-%Y-%m-%d.log'
log_rotation_age = 1d
log_rotation_size = 100MB
log_min_duration_statement = 1000
log_checkpoints = on
log_connections = off
log_disconnections = off
log_lock_waits = on
log_temp_files = 0
log_line_prefix = '%t [%p]: db=%d,user=%u,app=%a,client=%h '

# ----- Autovacuum -----------------------------------------------------------
autovacuum = on
autovacuum_max_workers = 3
autovacuum_naptime = 30s
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_scale_factor = 0.02
"#,
        preset = preset,
        ram = t.ram_mb,
        max_conn = t.max_connections,
        sb = t.shared_buffers_mb,
        ec = t.effective_cache_size_mb,
        wm = t.work_mem_mb,
        wsm = wal_sync_method,
        mws = t.max_wal_size_mb,
    )
}
