/// Render `pg_hba.conf`. The instance has exactly one app database (`db_name`)
/// and one app user (`app_user`), accessible only from inside the docker
/// network. The `pgbackrest` role is created via init SQL on first boot;
/// it uses local-socket trust because the container is the trust boundary.
pub fn generate_pg_hba(db_name: &str, app_user: &str) -> String {
    format!(
        r#"# Generated by pgforge — do not edit by hand.
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local unix socket — superuser app user trusted for admin tasks via docker exec.
local   all             {user}                                   trust

# pgBackRest runs as postgres OS user inside this container; trust over the
# local socket avoids needing a .pgpass file for archive-push.
local   replication     pgbackrest                              trust
local   all             pgbackrest                              trust

# Clone via pg_basebackup from a sibling container over the docker bridge
# network — host replication required for `pgforge clone`.
host    replication     pgbackrest      samenet                 scram-sha-256

# App user — only inside the docker network, password required.
host    {db}             {user}            samenet                 scram-sha-256

# Default-deny everything else.
host    all             all             all                     reject
"#,
        user = app_user,
        db = db_name,
    )
}
