/// Render `pg_hba.conf`. The instance has exactly one app database (`db_name`)
/// and one app user (`app_user`), accessible only from inside the docker network.
pub fn generate_pg_hba(db_name: &str, app_user: &str) -> String {
    format!(
        r#"# Generated by pgforge — do not edit by hand.
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local unix socket — superuser only, no password (container-internal).
local   all             postgres                                trust

# pgBackRest runs inside the same container as PG, over the local socket.
local   replication     pgbackrest                              scram-sha-256
local   all             pgbackrest                              scram-sha-256

# App user — only inside the docker network, password required.
host    {db}             {user}            samenet                 scram-sha-256

# Default-deny everything else.
host    all             all             all                     reject
"#,
        db = db_name,
        user = app_user,
    )
}
