/// Render the SQL run by the official postgres image's docker-entrypoint
/// at first init (placed in `/docker-entrypoint-initdb.d/`). Creates two
/// roles:
///   - `pgbackrest` — SUPERUSER, used locally for backup/archive operations.
///     Only reachable over the unix socket (`local` lines in pg_hba.conf).
///   - `pgreplica` — non-SUPERUSER, REPLICATION only. Used by `pgforge clone`
///     to pull a `pg_basebackup` over TCP from a sibling container. Exposing
///     a SUPERUSER role over TCP-SCRAM would be a lateral RCE vector, so the
///     replication role is deliberately separated and minimally privileged.
///
/// Both roles share the same password (kept simple — the security gain is
/// "TCP-exposed role has no SUPERUSER", not "different secrets per role").
/// The password is SQL-escaped (single quotes doubled) so it can contain
/// any character.
pub fn generate_init_sql(replication_password: &str) -> String {
    let escaped = replication_password.replace('\'', "''");
    format!(
        r#"-- Generated by pgforge — runs once on first cluster init.
CREATE ROLE pgbackrest WITH LOGIN REPLICATION SUPERUSER PASSWORD '{escaped}';
CREATE ROLE pgreplica  WITH LOGIN REPLICATION PASSWORD '{escaped}';
"#
    )
}
