/// Render the SQL run by the official postgres image's docker-entrypoint
/// at first init (placed in `/docker-entrypoint-initdb.d/`). Creates the
/// `pgbackrest` role used by archive_command and base backups.
///
/// The password is SQL-escaped (single quotes doubled) so it can contain
/// any character.
pub fn generate_init_sql(pgbackrest_password: &str) -> String {
    let escaped = pgbackrest_password.replace('\'', "''");
    format!(
        r#"-- Generated by pgforge — runs once on first cluster init.
CREATE ROLE pgbackrest WITH LOGIN REPLICATION SUPERUSER PASSWORD '{escaped}';
"#
    )
}
